config/routes.rb
Rails.application.routes.draw do
  get  'login/new',             to: 'logins#new', as: :new_login
  get  'login/cookiesrequired', to: 'logins#cookiesrequired', as: :cookiesrequired_login
  post 'login/create',          to: 'logins#create', as: :create_login
  get  'login/create',          to: redirect('/login/new')
  get  'login/destroy',         to: 'logins#destroy', as: :destroy_login

  post 'accounts/verify',       to: 'accounts#verify', as: :verify_account
  get  'accounts/setup/:token', to: 'accounts#setup',  as: :setup_account
  get  'accounts/:id/delete', to: 'accounts#delete',  as: :delete_account
  resources :accounts

  get 'lists/:id/edit_subscriptions', to: 'lists#edit_subscriptions', as: :edit_list_subscriptions
  get 'lists/:id/delete', to: 'lists#delete',  as: :delete_list
  resources :lists do
    get    'keys',              to: 'keys#index'
    get    'keys/:fingerprint', to: 'keys#show', as: :key
    delete 'keys/:fingerprint', to: 'keys#destroy'
    post   'keys',              to: 'keys#create', as: 'key_create'
  end
  resources  :subscriptions

  root 'accounts#home'

end

app/models/list.rb
class List < Base
  has_many :subscriptions
  add_response_method :http_response

  def to_s
    email
  end

  def keys(fingerprint=nil)
    params = {params: { list_id: self.id}}
    if fingerprint.present?
      Key.find(fingerprint, params)
    else
      Key.all(params)
    end
  end

  def key
    @key ||= Key.find(fingerprint, params: { list_id: self.id })
  end

  def headers_to_meta
    @headers_to_meta ||= Array(attributes['headers_to_meta']).join("\n")
  end

  def bounces_drop_on_headers
    Rails.logger.info "bdoh: #{attributes['bounces_drop_on_headers'].inspect}"
    @bounces_drop_on_headers ||= Hash(attributes['bounces_drop_on_headers'].attributes).map do |k,v|
      "#{k}: #{v}"
    end.join("\n")
  end

  def admins
    subscriptions.select do |subscription|
      subscription.admin?
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_load_and_authorize_resource only: :create

  def new
    @list = List.build
  end

  def index
    redirect_to root_path
  end

  def edit
    @keywords = %w[subscribe unsubscribe list-subscriptions set-fingerprint resend resend-encrypted-only sign-this add-key delete-key list-keys get-key fetch-key]
  end

  def show
    @subscription = current_account.subscription(@list)
  end

  def edit_subscriptions
    # Neccessary for the shared form.
    @subscription = Subscription.build
    # ActiveResource doesn't actually merge attributes given to build() (it's a
    # bug fixed for versions requiring rails5), so we assign the list manually.
    @subscription.list_id = @list.id
  end

  def create
    @old_timeout = List.timeout
    List.timeout = 120
    @list = List.new(new_list_params)
    authorize! :create, @list
    if @list.save
      if messages = List.connection.http_response.headers[:x_messages]
        flash[:error] = messages
      end
      redirect_to @list, notice: "✓ List created."
    else
      render 'new'
    end
  rescue ActiveResource::TimeoutError => exc
    logger.warn "Timeout while creating list: #{exc.inspect}"
    render 'timeout_on_create'
  ensure
    List.timeout = @old_timeout
  end

  def update
    logger.info list_params.inspect
    if @list.update_attributes(list_params)
      redirect_to edit_list_path(@list), notice: "✓ Options saved."
    else
      render 'edit'
    end
  end

  def destroy
    if list = @list.destroy
      redirect_to current_account, notice: "✓ List #{@list.email} deleted."
    else
      redirect_to list, error: "Deleting list failed!"
    end
  end

  private 

  def new_list_params
    params.require(:list).permit(:email, :fingerprint)
  end

  def list_params
    # TODO: Improve readability of this code.
    p = params.require(:list).permit!
    if p['headers_to_meta'].is_a?(String)
      p['headers_to_meta'] = p['headers_to_meta'].split("\n").map { |h| h.strip }
    end
    # TODO: Why are there sometimes empty values in these two keys?
    p['keywords_admin_only'] = p['keywords_admin_only'].map {|v| v.presence || nil }.compact
    p['keywords_admin_notify'] = p['keywords_admin_notify'].map {|v| v.presence || nil }.compact
    # Convert these into a hash.
    p['bounces_drop_on_headers'] = p['bounces_drop_on_headers'].to_s.strip.split("\n").inject({}) do |memo, line|
      name, value = line.split(':').map(&:strip)
      if name.present? && value.present?
        memo[name] = value
      end
      memo
    end
    p
  end
end

app/helpers/list_helper.rb
module ListHelper
  def table_row_title(subscription)
    title = []
    if subscription.admin?
      title << 'Admin'
    end
    if ! subscription.delivery_enabled?
      title << 'Delivery disabled'
    end
    title.join(', ')
  end
end

app/views/lists/_form.html.haml
.col-lg-6.col-md-8
  .panel.panel-info
    .panel-heading List-Options
    .panel-body
      = simple_form_for(@list, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
        = f.input :log_level, collection: %w[error warn info debug]
        = f.input :subject_prefix, hint: "If you want brackets, add them here, too."
        = f.input :subject_prefix_in, label: 'Subject-prefix for incoming emails', hint: "If you want brackets, add them here, too."
        = f.input :subject_prefix_out, label: 'Subject-prefix for outgoing emails', hint: "If you want brackets, add them here, too."
        = f.input :public_footer, as: :text
        = f.input :headers_to_meta, hint: "One header-name per line. Case-insensitive.", as: :text
        = f.input :bounces_drop_on_headers, placeholder: 'X-Spam-Flag: yes', hint: 'One match per line. Case-insensitive.', as: :text
        = f.input :keywords_admin_only, as: :check_boxes, collection: @keywords, hint: "Selected keywords may only be called by admins of this list.", wrapper: :horizontal_radio_and_checkboxes
        = f.input :keywords_admin_notify, as: :check_boxes, collection: @keywords, hint: "Admins will be notified whenever one of these keywords is called.", wrapper: :horizontal_radio_and_checkboxes

        = checkbox f, :send_encrypted_only, "Only send messages if they can be encrypted to their receiver."
        = checkbox f, :receive_encrypted_only, "Only accept encrypted messages?"
        = checkbox f, :receive_signed_only, "Only accept validly signed messages?"
        = checkbox f, :receive_authenticated_only, "Only accept messages that are validly signed by a subscriber? (Determined by fingerprint.)"
        = checkbox f, :receive_from_subscribed_emailaddresses_only, "Only accept messages with a subscribed address as From-header? (Warning: this is a very weak check!)"
        = checkbox f, :receive_admin_only, "Only accept messages validly signed by an admin of this list? (Determined by fingerprint.)"
        = checkbox f, :keep_msgid, "Pass incoming Message-IDs to outgoing messages? This enables threading in Mail-clients and helps to identify messages."
        = checkbox f, :bounces_drop_all, "Don't bounce but drop all rejected messages."
        = checkbox f, :bounces_notify_admins, "Notify admins of bounced messages."
        = checkbox f, :include_list_headers, "Include List-headers (RFC 2369) to outgoing messages."
        = checkbox f, :include_openpgp_header, "Include OpenPGP-headers to outgoing messages."
        = f.input :openpgp_header_preference, collection: %w[signencrypt encrypt sign], hint: "Only relevant if inclusion of OpenPGP-headers is active."
        = f.input :max_message_size_kb, hint: "Emails bigger than this will be rejected (measured in kilo-bytes.)"

        = f.button :submit, 'Update', class: 'btn btn-primary'

app/views/lists/_list.html.haml
= link_to list.email, list

app/views/lists/delete.html.haml
- @title = "Delete list"

%h3= @title

%p{style: 'margin: 3em 0'}
  %strong 
    Are you really sure?


= button_to "Delete list now!", @list, method: :delete, class: 'btn btn-danger'

app/views/lists/edit.html.haml
- @title = 'List options'

= render 'form'

app/views/lists/edit_subscriptions.html.haml
- @title = 'Subscriptions'

.col-lg-8.col-md-9
  .panel.panel-info
    .panel-heading Subscriptions
    .panel-body
      %table.table
        %thead
          %tr 
            %th email
            %th key
        %tbody
          - @list.subscriptions.each do |subscription|
            %tr{style: subscription.admin? && 'font-weight: bold'}
              %td{title: table_row_title(subscription)}
                = link_to(edit_subscription_path(subscription), title: 'Edit') do
                  - if subscription.delivery_enabled?
                    = subscription.email
                  - else
                    - surround('(', ')') do
                      = subscription.email
              %td
                - if subscription.fingerprint.blank?
                  %span.text-danger No key assigned!
                - elsif subscription.key.blank?
                  .mono= subscription.fingerprint
                  %span.text-danger Key not present!
                  %span
                    = link_to(list_keys_path(@list, anchor: 'upload'), title: 'Upload key', class: 'text-success') do
                      .large.glyphicon.glyphicon-upload
                - elsif subscription.key.trust_issues.present?
                  .mono= link_to subscription.fingerprint, list_key_path(@list, subscription.key)
                  %span.text-danger= subscription.key.trust_issues
                - else
                  .mono= link_to subscription.key.to_s, list_key_path(@list, subscription.key)
      .small.pull-right
        * (Delivery is disabled)
        %div{style: 'font-weight: bold'} * Admin of list

.col-lg-4.col-md-5
  .panel.panel-info
    .panel-heading New subscription
    .panel-body
      = render 'subscriptions/form'

app/views/lists/new.html.haml
- @title = 'New list'

.col-lg-6.col-md-8
  .panel.panel-info
    .panel-heading Create a new list
    .panel-body
      = simple_form_for(@list, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
        = f.input :email, hint: "Email-address for this list.", required: true
        = f.input :fingerprint, hint: "Optional: fingerprint of the existing OpenPGP public key to use for this list. A new key-pair will be generated if this is blank or no matching key is found."
        = f.button :submit, 'Create', class: 'btn btn-success'

app/views/lists/show.html.haml
-# There's no assignment of @title on purpose, showing only the listname is a good title for this page.

- if @list.key.blank?
  .alert.alert-warning 
    %strong No key present! This list is not functional!

.col.col-lg-6.col-md-8
  .panel.panel-info
    .panel-heading= @list
    .panel-body
      %table.table
        %tr
          %td Key of list
          %td= link_to("0x#{@list.key.fingerprint}", [@list, @list.key])
        %tr
          %td Admins
          %td
            - if @list.admins.blank?
              .text-danger None
            - else
              - @list.admins.each do |subscription|
                - if can? :show, subscription
                  = link_to(subscription, edit_subscription_path(subscription))
                - else
                  = subscription
        %tr
          %td # of subscriptions
          %td
            - if can? :index, @list.subscriptions
              = link_to @list.subscriptions.count, edit_list_subscriptions_path(@list)
            - else
              = @list.subscriptions.count

        - if can? :manage, @list
          %tr
            %td Subscriptions without key
            %td
              - @list.subscriptions.select { |sub| sub.key.blank? }.each do |subscription|
                = link_to(subscription, edit_subscription_path(subscription))
              - end.join(', ')

- if can? :destroy, @list
  .col.col-lg-6.col-md-4
    .pull-right
      = link_to "Delete list", delete_list_path(@list), class: 'text-danger'

app/views/lists/timeout_on_create.html.haml
%h1 Time out.

%p We waited for a long time but the Schleuder API didn't answer. This happens sometimes when creating a new list because generating a new OpenPGP key-pair (for the new list) requires a lot of randomness — if that's not given, GnuPG just waits until there's more.

%p
  Unfortunately we can't see from here what the issue really is. But chances are that the list was created just fine and in a few minutes the new OpenPGP key-pair will have been generated, too. So please wait a little while and then
  = link_to root_path, 'have a look if your list was created.'