config/routes.rb
Rails.application.routes.draw do
  get  'login/new',             to: 'logins#new', as: :new_login
  get  'login/cookiesrequired', to: 'logins#cookiesrequired', as: :cookiesrequired_login
  post 'login/create',          to: 'logins#create', as: :create_login
  get  'login/create',          to: redirect('/login/new')
  get  'login/destroy',         to: 'logins#destroy', as: :destroy_login

  post 'accounts/verify',       to: 'accounts#verify', as: :verify_account
  get  'accounts/setup/:token', to: 'accounts#setup',  as: :setup_account
  get  'accounts/:id/delete', to: 'accounts#delete',  as: :delete_account
  resources :accounts

  get 'lists/:id/edit_subscriptions', to: 'lists#edit_subscriptions', as: :edit_list_subscriptions
  get 'lists/:id/delete', to: 'lists#delete',  as: :delete_list
  resources :lists do
    get    'keys',              to: 'keys#index'
    get    'keys/:fingerprint', to: 'keys#show', as: :key
    delete 'keys/:fingerprint', to: 'keys#destroy'
    post   'keys',              to: 'keys#create', as: 'key_create'
  end
  resources  :subscriptions

  root 'accounts#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate
  before_filter :set_locale
  load_and_authorize_resource
  # ensure authorization is checked.
  check_authorization

  helper_method :current_account
  helper_method :current_user

  rescue_from ActiveRecord::RecordNotFound, ActiveResource::ResourceNotFound do |exception|
    render_404
  end

  rescue_from CanCan::AccessDenied do |exception|
    render 'errors/403', :status => :forbidden
  end

  rescue_from ActiveResource::ForbiddenAccess do |exception|
    logger.error "API denied access! Check if the fingerprint of your certificate has been added to the list of fingerprints at the schleuder-server."
    render 'errors/api_denied', :status => :forbidden
  end

  # Happens when fingerprint verification failed.
  rescue_from ActiveResource::SSLError do |exception|
    logger.error "SSLError: #{exception.inspect}"
    case exception.message
    when /certificate verify failed/
      @reason = "The API sent different TLS-fingerprint than we expected, check your settings."
    else
      @reason = exception.message
    end
    render 'errors/ssl_error', :status => :forbidden
  end

  rescue_from ActiveResource::BadRequest do |exc|
    logger.error "API response: #{exc.response}"
    logger.error "API response headers: #{exc.response.to_hash.inspect}"
    logger.error "API response body: #{exc.response.body}"
    raise exc
  end

  rescue_from Errno::ECONNREFUSED do |exc|
    logger.error exc.inspect
    logger.error exc.backtrace.join("\n")
    render 'errors/missing_schleuder_api', status: 500
  end

  rescue_from ActiveResource::TimeoutError do |exc|
    logger.error exc.inspect
    logger.error exc.backtrace.join("\n")
    render 'errors/timeout', status: 500
  end

  private

  def render_404
    render 'errors/404', :status => :not_found
  end

  def current_account
    @current_account ||= session[:current_account_id] &&
        Account.find(session[:current_account_id])
  end
  # Many expect current_user()
  alias_method :current_user, :current_account

  def current_account=(account)
    @current_account = account
  end

  def update_session_expiry
    if current_account
      session[:login_expires_at] = 30.minutes.from_now
    end
  end

  def authenticate
    expiry = Time.parse(session[:login_expires_at])
    if current_account && expiry > Time.now
      update_session_expiry
    else
      session[:return_to] = request.fullpath
      log_out t("please_log_in")
    end
  rescue => e
    logger.error "Error: #{e}"
    log_out "Error.", :error
  end

  def set_locale
    if params['lang'].present?
      lang_param = params['lang'].to_sym
      if I18n.available_locales.include?(lang_param)
        I18n.locale = lang_param
      end
    end
  end

  def log_out(msg, msg_type=:notice)
    current_account = session[:current_account_id] = nil
    redirect_to new_login_url, msg_type => msg
  end

  def load_resource
    var_name = controller_name.singularize
    var = controller_name.classify.constantize.find(params[:id])
    instance_variable_set("@#{var_name}", var)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def make_breadcrumb
    url_for.split('/').map do |part|
      # Skip IDs, we use the instance variable to go easier on the database.
      next if part.to_i > 0 || part.blank?

      obj = instance_variable_get("@#{part.singularize}")
      # Don't link action's names ("edit").
      next if obj.blank? && !current_page?(action: :index)

      index_url = url_for(controller: part, action: :index)
      index_name = part.humanize.pluralize.titleize
      out = bc_part(index_name, index_url)

      if obj
        if obj.id
          obj_url = url_for(controller: part, action: :show, id: obj.id)
          out << bc_part(obj.email, obj_url)
        else
          out << bc_part(obj.email.presence || 'New', nil)
        end
      end
      out
    end.compact.join.html_safe
  end

  def bc_part(name, url)
    " » #{link_to_unless(current_page?(url), name, url)}"
  end

  def key_as_ascii(key)
    GPGME::Key.export key.fingerprint, armor: true
  end

  def checkbox(form, field, hint)
    label = "#{field.to_s.humanize}?"
    form.input field, label: label, hint: hint, as: :boolean, wrapper: :horizontal_boolean
  end

  def generate_h1
    t = "Schleuder"
    if @title.present?
      t << " ★ #{@title}"
    end
    if @list.present?
      t << " ★ #{@list.email}"
    end
    t
  end
end

app/views/application/_breadcrumb.html.haml
- if current_user.present?
  .breadcrumb= make_breadcrumb

app/views/application/_flashes.html.haml
- flash.each do |name, msgs|
  - Array(msgs).each do |msg|
    = content_tag :div, :class => "alert alert-#{name.to_sym == :error ? "danger" : "success" } alert-dismissable" do
      %button.close{:type => "button", :data => {:dismiss => "alert"}, :aria => {:hidden => "true"} } &times;
      = msg

app/views/application/_list_menu.html.haml
%ul#listmenu
  - if can?(:update, @list)
    %li
      %span.glyphicon.glyphicon-th-list
      = link_to_unless_current(t(".subscriptions"), edit_list_subscriptions_path(@list), accesskey: :s)
    %li
      %span.glyphicon.glyphicon-wrench
      = link_to_unless_current(t(".list_options"), edit_list_path(@list), accesskey: :o)
  - else
    %li
      %span.glyphicon.glyphicon-th-list
      = link_to_unless_current(t(".edit_subscription"), edit_subscription_path(@subscription), accesskey: :s)
  %li
    %span.glyphicon.glyphicon-barcode
    = link_to_unless_current(t(".keys"), list_keys_path(@list), accesskey: :k)

app/views/application/_navbar.html.haml
- if current_user.present?
  %ul.nav.navbar-nav.navbar-right
    %li
      = link_to(root_path, accesskey: :h) do
        %span.glyphicon.glyphicon-user
        =current_user.email
    %li
      = link_to(edit_account_path(current_user)) do
        %span.glyphicon.glyphicon-wrench
        = t(".account_settings")
    %li
      = link_to(destroy_login_path) do
        %span.glyphicon.glyphicon-log-out
        = t(".logout")

app/views/application/_page_header.html.haml
.page-header
  - if @list.present? && @list.persisted?
    #pageheadline= link_to_unless current_page?(@list), @list, @list, accesskey: :l
    = render 'list_menu'
  - else
    #pageheadline= @title