config/routes.rb
Rails.application.routes.draw do
  get  'login/new',             to: 'logins#new', as: :new_login
  get  'login/cookiesrequired', to: 'logins#cookiesrequired', as: :cookiesrequired_login
  post 'login/create',          to: 'logins#create', as: :create_login
  get  'login/create',          to: redirect('/login/new')
  get  'login/destroy',         to: 'logins#destroy', as: :destroy_login

  post 'accounts/verify',       to: 'accounts#verify', as: :verify_account
  get  'accounts/setup/:token', to: 'accounts#setup',  as: :setup_account
  get  'accounts/:id/delete', to: 'accounts#delete',  as: :delete_account
  resources :accounts

  get 'lists/:id/edit_subscriptions', to: 'lists#edit_subscriptions', as: :edit_list_subscriptions
  get 'lists/:id/delete', to: 'lists#delete',  as: :delete_list
  resources :lists do
    get    'keys',              to: 'keys#index'
    get    'keys/:fingerprint', to: 'keys#show', as: :key
    delete 'keys/:fingerprint', to: 'keys#destroy'
    post   'keys',              to: 'keys#create', as: 'key_create'
  end
  resources  :subscriptions

  root 'accounts#home'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, email: true

  def to_s
    email
  end

  def superadmin?
    self.email == 'root@localhost'
  end

  def subscribed_to?(list)
    lists.include?(list)
  end

  def subscriptions
    @subscriptions ||= Subscription.where(email: self.email)
  end

  def subscription(list)
    Subscription.where(email: self.email, list_id: list.id).first
  end

  def lists
    subscriptions.map(&:list)
  end

  def admin_lists
    Subscription.where(email: self.email, admin: true).map(&:list)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_filter :authenticate, only: [:new, :verify, :setup, :create]
  skip_load_resource only: [:verify, :setup, :create]
  before_filter :validate_turing_answer, only: :verify

  def index
    redirect_to root_path
  end

  def home
    @account = current_account
    show
    render 'show'
  end

  def new
    if TuringQuestion.available?
      @turing_question = TuringQuestion.random
      session[:turing_question_id] = @turing_question.id
    end
    @account = Account.new(email: session[:account_email])
    session[:account_email] = nil
  end

  def verify
    @email = params[:account][:email]
    if Account.where(email: @email).present?
      return redirect_to_new(t(".address_already_registered"))
    end

    ac_req = AccountRequest.create(email: @email)
    mail = AccountMailer.send_verification_link(@email, ac_req.token)
    if ! res = mail.deliver_now
      redirect_to_new(res)
    end
  rescue Errno::ECONNREFUSED => exc
    logger.error exc.message
    redirect_to_new(t(".smtp_connection_refused", error: exc.message))
  end

  def setup
    ac_req = AccountRequest.find_by_token!(params[:token])

    if ! ac_req.still_valid?
      render text: t(".token_too_old")
      ac_req.destroy
      return
    end

    @account = Account.new
    @account.email = ac_req.email
    @token = ac_req.token
  end

  def create
    ac_req = AccountRequest.find_by_token!(params[:token])
    if ! res = ac_req.destroy
      logger.error "Deleting AccountRequest failed: #{res.inspect} —— AccountRequest: #{ac_req.inspect}"
      redirect_to setup_account_path, alert: t("something_went_wrong")
      return
    end

    @account = Account.new(account_params)
    @account.email = ac_req.email
    if @account.save
      redirect_to new_login_path, notice: t(".success")
    else
      render 'setup'
    end
  end

  def update
    if @account.update(account_params)
      redirect_to @account, notice: t(".password_changed")
    else
      render :edit
    end
  end

  def show
    @subscribed_lists = @account.lists
    @admin_lists = if @account.superadmin?
                     List.all
                   else
                     @account.admin_lists
                   end
    @lists = @subscribed_lists | @admin_lists
  end

  def destroy
    if account.superadmin?
      redirect_to account, alert: t(".superadmin_not_deletable")
      return
    end

    if account = @account.destroy
      log_out t(".success")
    else
      logger.error "Deleting account failed: #{account.inspect}"
      redirect_to account, alert: t(".failure")
    end
  end

  private

  def validate_turing_answer
    turing_question = TuringQuestion.find(session[:turing_question_id])
    session[:turing_question_id] = nil
    if turing_question.blank?
      return redirect_to_new(t("something_went_wrong"))
    end

    if turing_question.valid_answer?(params[:turing_answer])
      true
    else
      redirect_to_new(t(".invalid_answer"))
    end
  end

  def redirect_to_new(error_message)
    flash[:error] = error_message
    session[:account_email] = params[:account][:email]
    redirect_to new_account_path
    false
  end

  def render_404
    if params[:token].present?
      render 'error_404', :status => :not_found
    else
      super
    end
  end

  def account_params
    params.require(:account).permit(:password, :password_confirmation)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/delete.html.haml
- @title = "Delete account #{@account}"

%h3= @title

%p{style: 'margin: 3em 0'}
  %strong 
    Are you really sure? This does 
    %em NOT
    unsubscribe you from any list!


= button_to "Delete account now!", @account, method: :delete, class: 'btn btn-danger'

app/views/accounts/edit.html.haml
- @title = 'My account'

.col-lg-6.col-md-8.col-sm-12
  .panel.panel-info
    .panel-heading Change password
    .panel-body
      = simple_form_for(@account, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
        = f.input :password, as: :password, required: true
        = f.input :password_confirmation, as: :password, required: true

        = f.submit 'Save', class: 'btn btn-primary'

- if ! @account.superadmin?
  .col-lg-6.col-md-8
    .panel.panel-danger
      .panel-heading Delete Account
      .panel-body
        = link_to "Delete account", delete_account_path(@account), class: 'text-danger'

app/views/accounts/error_404.html.haml
%h1= t(".headline")

= simple_format(t(".explanation", link: link_to(t(".link_text"), new_account_url)).html_safe)

app/views/accounts/new.html.haml
- @title = t(".headline")

.col-lg-6.col-md-8
  = simple_form_for(@account, url: verify_account_path, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
    = f.input :email, hint: t(".email_hint")
    - if @turing_question.present?
      #turing-question.form-group
        %label.control-label.col-sm-3{for: :turing_answer}= @turing_question.question
        .col-sm-9
          = text_field_tag :turing_answer, '', class: 'form-control'
          %p.help-block= t(".turing_question_hint")

    = f.submit t(".button"), class: 'btn btn-primary'

app/views/accounts/setup.html.haml
.page-header
  %h1 Create account for #{@account}

.col-lg-5
  To complete the sign-up please choose a password for #{@account}.

  = simple_form_for(@account, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
    .form-group
      = text_field_tag 'token', @token, hidden: true
      = f.input :password
      = f.input :password_confirmation

    = f.submit 'Create Account', class: 'btn btn-primary'

  %em Note: this account and its passsword are only known to this web-interface, not to any mailing-list.

app/views/accounts/show.html.haml
- @title = 'Home'

- if @lists.present?
  .col-lg-4
    .panel.panel-info
      .panel-heading Lists
      .panel-body
        %ul
          -@lists.each do |list|
            - if @admin_lists.include?(list)
              %li
                %em= link_to list, list
            -else
              %li= link_to list, list
      - if @admin_lists.any?
        .panel-footer
          Lists you are administrating are
          %em emphasized

.clearfix

- if can? :create, List
  = link_to(new_list_path, class: 'btn btn-success') do
    %span.glyphicon.glyphicon-plus
    New list

app/views/accounts/verify.html.haml
.page-header
  %h1 Verification request sent to #{@email}

Please check your mailbox and click the link you received from &lt;#{Conf.mailer_from}&gt;.